### ISSUE TITLE
Problem combining unset with other commands

### ISSUE THREAD

**Issue by uturnr** [hoytech/update-immutable#5]
I found that when using both splice and unset in one update, only unset works.

```
update( { a: { b: 1 }, c: [2] }, { c: { $splice: [ [ 0, 1 ] ] }, $unset: 'a' } );
=> { c: [2] }
```

Unexpected behaviour happens with other combinations as well:

```
update( { a: { b: 1 }, c: [2] }, { c: { $set: 'dog' }, $unset: 'a' } );
=> { c: [2] }
```

```
update( { a: { b: 1 }, c: [2] }, { a: { $unset: 'b' }, $unset: 'c' } );
=> { a: { b: 1 } }
```

In another, unset worked as expected in combination with another command:

```
update( { a: { b: 1 }, c: [2] }, { a: { $unset: 'b' }, c: { $set: 'dog'} } );
=> { a: {}, c: 'dog' }
```

**Comment by hoytech** [comment]
Thanks! This is a bug, I'll try to fix it ASAP. For now, you could perform it as 2 separate updates.

**Comment by hoytech** [comment]
Thank you very much for the report and for the test-cases. I have fixed the bug and added the test-cases to the test-suite: https://github.com/hoytech/update-immutable/blob/6382bd6065965ac5ca8006c8142319b9693b7c3f/t/basic.js#L428-L447

The problem was that the behaviour of multiple commands or keys to recurse into at the same level wasn't fully implemented (or even specified). I have implemented the cases you suggest and a few others that made sense. I've also added some new docs on this topic here:

https://github.com/hoytech/update-immutable#multiple-updates

I just pushed version 1.4.0 to npm, can you please upgrade and let me know if it fixes your problem?

**Comment by uturnr** [comment]
Wow, that was quick! I have updated to 1.4.0 and it solves my problem. Thank you!
